import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <head>
        <title>Landing Abogado</title>
        <meta name="description" content="Landing de un abogado proyecto - Prueba." />
        <meta name="keywords" content="landindg, abogado" />
        <meta name="author" content="Dany Rivera" />
        <link rel="icon" href="/logo.webp" />
        <link rel="apple-touch-icon" href="/logo-app.png"></link>
      </head>
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
      >
        {children}
      </body>
    </html>
  );
}
